apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name | default "hello-world" }}
  labels:
    run: {{ .Values.application.name | default "hello-world" }}
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: {{ .Values.application.name | default "hello-world" }}
  type: LoadBalancer
